import Image from 'next/image';
import { FaLeaf } from "react-icons/fa6";
import { MdPlayArrow } from "react-icons/md";

export default function EnvironmentalSustainability() {
  return (
    <div className="px-4 sm:px-6 lg:px-8 py-8 sm:py-12 text-white container mx-auto">
      {/* Heading */}
      <h2 className="text-2xl sm:text-3xl lg:text-4xl font-bold text-orange-500 mb-6 ">
        <FaLeaf className='inline-block mr-2 text-orange-500' /> Environmental Sustainability
      </h2>

      {/* Carbon Offset Program and Eco-friendly Initiatives */}
      <div className="grid grid-cols-1 xl:grid-cols-2 gap-6 sm:gap-8">
        {/* Carbon Offset Program */}
        <div className="flex flex-col md:flex-row items-center gap-4 sm:gap-6 p-4 sm:p-6 bg-black rounded-lg shadow-md">
          <Image
            src="/social-responsibilty/carbon-offset.webp"
            width={250}
            height={500}
            alt="Carbon Offset Program"
            className="rounded-lg sm:w-[80%] md:w-[300px] lg:w-[350px] xl:w-[400px] h-auto"
          />
          <div>
            <h3 className="text-lg sm:text-xl font-bold text-orange-500 mb-2">
              <MdPlayArrow className='inline-block mr-2 text-orange-500' />
              Carbon Offset Program
            </h3>
            <p className="text-sm sm:text-base text-justify">
              As a leading travel and tourism company, we recognize the imperative to address carbon footprint and mitigate the environmental impact of our operations. We are committed to taking proactive steps towards sustainability by implementing a comprehensive Carbon Offset Program. The initiative aims to neutralize the greenhouse gas emissions generated by our activities, thereby contributing to the global fight against climate change while offering travelers the opportunity to participate in responsible travel experiences.
            </p>
          </div>
        </div>

        {/* Eco-friendly Initiatives */}
        <div className="flex flex-col md:flex-row items-center gap-4 sm:gap-6 p-4 sm:p-6 bg-black rounded-lg shadow-md">
          <Image
            src="/social-responsibilty/eco-tourism.webp"
            width={300}
            height={500}
            alt="Eco-friendly Initiatives"
            className="rounded-lg w-full md:w-[300px] h-auto"
          />
          <div>
            <h3 className="text-lg sm:text-xl font-bold text-orange-500 mb-2">
              <MdPlayArrow className='inline-block mr-2 text-orange-500' />
              Eco-friendly Initiatives
            </h3>
            <p className="text-sm sm:text-base text-justify">
              From implementing energy-efficient technologies in our offices to reducing single-use plastics in our tours, and paper for documentation, we are committed to minimizing waste and promoting eco-friendly alternatives. This involves digitizing documents and processes, reducing reliance on physical paper, thus fostering efficiency and sustainability while minimizing environmental impact. We have transitioned from traditional paper business cards to innovative biodegradable digital cards for all our employees. This eco-friendly approach aligns with our commitment to sustainability and minimizes our environmental footprint. Leveraging on our technological advancements, our goal is to achieve complete paperless operations by 2028.
            </p>
          </div>
        </div>
      </div>

      {/* Responsible Tourism */}
      <div className="mt-8 flex flex-col md:flex-row items-center gap-4 sm:gap-6 p-4 sm:p-6 bg-black rounded-lg shadow-md">
        <Image
          src="/social-responsibilty/responsible-tourism.webp"
          width={650}
          height={250}
          alt="Responsible Tourism"
          className="rounded-lg shadow-sm w-full sm:w-[600px] h-auto"
        />
        <div>
          <h3 className="text-lg sm:text-xl font-bold text-orange-500 mb-2">
            <MdPlayArrow className='inline-block mr-2 text-orange-500' />
            Responsible Tourism
          </h3>
          <p className="text-sm sm:text-base text-justify">
            We partner with local communities and organizations to promote responsible tourism practices that respect cultural heritage, protect wildlife, and support sustainable livelihoods.
          </p>
        </div>
      </div>
    </div>
  );
}